version: "3.3"

services:
  frontend:
    build: ./womparator/frontend
    volumes:
      - ./womparator/frontend:/usr/src/app
    depends_on:
      - backend
    ports:
      - "${WOMP_FRONT_PORT}:3000"
  backend:
    build: ./womparator/backend
    volumes:
      - ./womparator/backend:/app
    ports:
      - "${WOMP_BACK_PORT}:8080"
