name: Docker Compose CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest
    container: docker/compose

    steps:
    - uses: actions/checkout@v3

    - name: Building docker container
      run: docker-compose build
    - name: Starting
      run: docker-compose up -d

    - name: Cleanup docker
      run: docker-compose down
